storage: Add avro.jar to the HADOOP_CLASSPATH.
Hadoop clusters use to use avro 1.7.4 instead of 1.7.7
With the old version, generated code in biodata-models cant be used due to:
    java.lang.NoSuchMethodError: org.apache.avro.Schema$Parser.parse(Ljava/lang/String;[Ljava/lang/String;)Lorg/apache/avro/Schema;